GET http://localhost:5005/accounts

###

POST http://localhost:5005/accounts
Content-Type: application/json

{
    "AccountNumber": "12345678913345678911",
    "Balance": 0.0   
}   

###
GET  http://localhost:5005/check_balance/12345678913345678911
